project:
  title: "report"
  output-dir: "_output"

standalone: true
self-contained: true

# Julia support
engine: julia

julia:
  exeflags: ["--project=../project"]

execute:
  daemon: false

# Generic options
lang: ru-RU
number-sections: true

toc: true
toc-title: "Содержание"
toc-depth: 2

# Cross-reference customization
crossref:
  lof-title: "Список иллюстраций"
  lot-title: "Список таблиц"
  lol-title: "Листинги"

# Bibliography
bibliography:
  - bib/cite.bib

csl: _resources/csl/gost-r-7-0-5-2008-numeric.csl

# Output formats
format:

  # DOCX
  docx:
    toc: true
    number-sections: true
    toc-depth: 2

  # PDF
  pdf:
    toc: true
    number-sections: true
    colorlinks: false
    toc-depth: 2

    # Lists
    lof: true
    lot: true

    # Document
    documentclass: scrreprt
    papersize: a4
    fontsize: 12pt
    linestretch: 1.5

    # Language
    babel-lang: russian
    babel-otherlangs: english

    # Bibliography
    cite-method: biblatex
    biblio-style: gost-numeric

    biblatexoptions:
      - backend=biber
      - langhook=extras
      - autolang=other*

    # Miscellaneous
    csquotes: true
    indent: true

    include-in-header:
      - file: _resources/tex/preamble.tex
